name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Configure
      run: pip install sphinx
      
    - name: Install dependencies
      run: |
        make html
        pwd
        git status
        git fetch origin Publish
        git checkout Publish
        echo "Copying..."
        pwd
        ls -l
        cp -r build/html/* docs/
        git commit -am "Add new build files"
        git config  user.name "github ci"
        git push
