name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Configure
      run: pip install sphinx
      
    - name: Install dependencies
      run: |
        make html
        cd build/html
        pwd
