name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Configure
      run: pip install sphinx
      
    - name: make HTML
      run: |
        make html
    - name: Checkout Publish
      run: |
        git fetch origin Publish
        git checkout Publish
        git pull
    - name: Copy build artifacts
      run: |
        cp -r build/html/* docs/
        git add -A
    - name: Commit and push
      run: |
        git config  user.name "github-actions"
        git commit -am "Add new build files"
        git push
