name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Configure
      run: pip install sphinx
      
    - name: Install dependencies
      run: |
        make html
        pwd
        git status
        git fetch origin Publish
        git checkout Publish
        echo "Before Copy..."
        ls -l docs/
        echo "Copy ..."
        cp -r build/html/* docs/
        echo "After Copy..."
        ls -l docs/
        git add -A
        echo "Commit ..."
        git config  user.name "github ci"
        git commit -am "Add new build files"
        echo "Push..."
        echo ${{ secrets.GITHUB_TOKEN }}
        git push
